/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dominio.Estoque;
import dominio.Funcionario;
import dominio.ItensVenda;
import dominio.Venda;
import dominio.dados.EstoqueJpaController;
import dominio.dados.FuncionarioJpaController;
import dominio.dados.VendaJpaController;
import dominio.dados.exceptions.NonexistentEntityException;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import util.ButtonColumn;
import util.Util;

/**
 *
 * @author 275322
 */
public class TelaVendas extends javax.swing.JFrame {

    /**
     * Creates new form TelaVendas
     */
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("JobSmart-DesktopPU");
    VendaJpaController vjc = new VendaJpaController(emf);
    FuncionarioJpaController fjc = new FuncionarioJpaController(emf);
    EstoqueJpaController ejc = new EstoqueJpaController(emf);
    Funcionario funcionario;
    Venda venda;
    List<ItensVenda> itensVenda = new ArrayList<>();
    JButton btnRemoverItem;
    Estoque est;
    boolean stop = true;
    int counter = 0;

    public TelaVendas() {
        System.out.println("Ponto A");
        initComponents();
    }

    public TelaVendas(Funcionario funcionario) {
        this.funcionario = funcionario;
        venda = new Venda((vjc.getVendaCount() + 1), new Date(), funcionario);
        System.out.println(venda.getMatFun());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoCodigo = new javax.swing.JTextField();
        campoQuantidade = new javax.swing.JSpinner();
        campoCategoria = new javax.swing.JTextField();
        campoNomeProduto = new javax.swing.JTextField();
        btnFinalizarCompra = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoUltimoProduto = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        adicionarProduto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuLogo = new javax.swing.JMenu();
        menuVendas = new javax.swing.JMenu();
        menuCadastro = new javax.swing.JMenu();
        menuCadastroProdutos = new javax.swing.JMenuItem();
        menuCadastroEstoque = new javax.swing.JMenuItem();
        menuConsulta = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 768));

        campoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoActionPerformed(evt);
            }
        });
        campoCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoCodigoKeyReleased(evt);
            }
        });

        campoQuantidade.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        campoQuantidade.setToolTipText("1");
        campoQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoQuantidadeKeyReleased(evt);
            }
        });

        campoCategoria.setEnabled(false);

        campoNomeProduto.setEnabled(false);
        campoNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeProdutoActionPerformed(evt);
            }
        });

        btnFinalizarCompra.setBackground(new java.awt.Color(0, 153, 0));
        btnFinalizarCompra.setText("Finalizar Compra");
        btnFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarCompraActionPerformed(evt);
            }
        });

        campoUltimoProduto.setEditable(false);
        jScrollPane2.setViewportView(campoUltimoProduto);

        jLabel2.setText("Codigo");

        jLabel3.setText("Nome do Produto");

        jLabel4.setText("Categoria");

        jLabel6.setText("Ultimo Produto");

        jLabel7.setText("Quantidade");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cancelar", "Código", "Quant.", "Nome", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setMinWidth(20);
            tabela.getColumnModel().getColumn(0).setMaxWidth(40);
            tabela.getColumnModel().getColumn(2).setMaxWidth(80);
            tabela.getColumnModel().getColumn(3).setMinWidth(200);
        }

        adicionarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        adicionarProduto.setText("Adicionar Produto");
        adicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarProdutoActionPerformed(evt);
            }
        });
        adicionarProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                adicionarProdutoKeyReleased(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/JOBSMART_SMALL.png"))); // NOI18N
        jLabel1.setToolTipText("");

        menuLogo.setText("Home");
        menuLogo.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuLogoMenuSelected(evt);
            }
        });
        jMenuBar1.add(menuLogo);

        menuVendas.setText("Vendas");
        jMenuBar1.add(menuVendas);

        menuCadastro.setText("Cadastro");
        menuCadastro.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuCadastroMenuSelected(evt);
            }
        });

        menuCadastroProdutos.setText("Produtos");
        menuCadastroProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroProdutosActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroProdutos);

        menuCadastroEstoque.setText("Estoque");
        menuCadastroEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroEstoqueActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroEstoque);

        jMenuBar1.add(menuCadastro);

        menuConsulta.setText("Consulta");
        menuConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuConsulta.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuConsultaMenuSelected(evt);
            }
        });
        jMenuBar1.add(menuConsulta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFinalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(119, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campoQuantidade))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adicionarProduto))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adicionarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                        .addComponent(btnFinalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarCompraActionPerformed

        if (campoCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencha o campo 'codigo'!");
        } else {
            if (itensVenda.size() < 1) {
                JOptionPane.showMessageDialog(this, "Adicione o produto antes de finalizar!!");
            } else {
                venda.setItensVendaList(itensVenda);
                venda.setVlrVenda(valorVenda(itensVenda));
                itensVenda = new ArrayList<>();
                new TelaPagamento(venda).setVisible(true);
                zerarComponentes();
            }
        }
    }//GEN-LAST:event_btnFinalizarCompraActionPerformed

    private void campoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoActionPerformed

    private void campoNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeProdutoActionPerformed

    private void menuLogoMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuLogoMenuSelected
        this.dispose();
    }//GEN-LAST:event_menuLogoMenuSelected

    private void menuCadastroMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuCadastroMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastroMenuSelected

    private void menuCadastroProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroProdutosActionPerformed
        Util.instanciaCadastroProduto(this, funcionario);
    }//GEN-LAST:event_menuCadastroProdutosActionPerformed

    private void menuCadastroEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroEstoqueActionPerformed
        Util.instanciaCadastroEstoque(this, funcionario);
    }//GEN-LAST:event_menuCadastroEstoqueActionPerformed

    private void menuConsultaMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuConsultaMenuSelected
        Util.instanciaConsultaProduto(this, funcionario);
    }//GEN-LAST:event_menuConsultaMenuSelected

    private void adicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarProdutoActionPerformed
        adicionarProduto();
    }//GEN-LAST:event_adicionarProdutoActionPerformed

    private void campoCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCodigoKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            adicionarProduto();
        }
    }//GEN-LAST:event_campoCodigoKeyReleased

    private void campoQuantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoQuantidadeKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            adicionarProduto();
        }
    }//GEN-LAST:event_campoQuantidadeKeyReleased

    private void adicionarProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adicionarProdutoKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            adicionarProduto();
        }
    }//GEN-LAST:event_adicionarProdutoKeyReleased
    private void adicionarProduto() {
        int codigoEstoque = Integer.parseInt(campoCodigo.getText());
        est = ejc.findEstoque(codigoEstoque);
        if (!validarQuantidade(est)) {
            JOptionPane.showMessageDialog(this, "Quantidade inserida maior do que a do estoque, que é " + est.getQtdProdEst());
        } else {
            campoNomeProduto.setText(est.getIdProd().getNmProd());
            campoCategoria.setText(est.getIdProd().getIdCat().getNmCat());
            if (est.setVlrVendaEst()) {
                try {
                    ejc.edit(est);
                } catch (NonexistentEntityException ex) {
                    Logger.getLogger(TelaVendas.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(TelaVendas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (!validarCodigoDuplicado(est)) {
                definirEAdicionarItem();
            } else {
                if (validarQuantidade(est)) {
                    atualizarQuantidade(est);
                }
            }

        }

    }

    public boolean validarQuantidade(Estoque est) {
        if (((int) campoQuantidade.getValue()) > est.getQtdProdEst()) {
            return false;
        }
        return true;

    }

    public boolean validarCodigoDuplicado(Estoque est) {
        for (ItensVenda item : itensVenda) {
            if (est.equals(item.getIdEst())) {
                return true;
            }
        }
        return false;
    }

    public void definirEAdicionarItem() {
        ItensVenda item = new ItensVenda();
        item.setIdEst(est);
        item.setQuantItensVenda((Integer) campoQuantidade.getValue());
        itensVenda.add(item);
        gerarTabela(item);

    }

    public void atualizarQuantidade(Estoque est) {
        ItensVenda itemSubs = new ItensVenda();
        Integer index = null;
        for (ItensVenda item : itensVenda) {
            if (est.equals(item.getIdEst())) {
                System.out.println("Quantidade atual>:" + item.getQuantItensVenda());
                itemSubs = item;
                itemSubs.setIdEst(est);
                int quantidadeReal = itemSubs.getQuantItensVenda() + (Integer) campoQuantidade.getValue();
                if (quantidadeReal > est.getQtdProdEst()) {
                    JOptionPane.showMessageDialog(this, "Quantidade inserida maior do que a do estoque, que é " + est.getQtdProdEst());
                    break;
                }
                itemSubs.setQuantItensVenda(quantidadeReal);
                index = itensVenda.indexOf(item);
                break;
            }
        }
        if (index != null) {
            itensVenda.set(index, itemSubs);
            gerarTabela(itensVenda.get(index));
            removerLinha();
        }
    }

    public void gerarTabela(ItensVenda item) {
        btnRemoverItem = new JButton();
        Action act = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        };
        ButtonColumn testeBtn = new ButtonColumn(tabela, act, 0);
        Object[] obj = {"X", est.getIdEst(), item.getQuantItensVenda(),
            est.getIdProd().getNmProd(), (est.getVlrVendaEst() * item.getQuantItensVenda())};

        DefaultTableModel modelCadastro = (DefaultTableModel) tabela.getModel();
        modelCadastro.addRow(obj);
        campoUltimoProduto.setText((((String) modelCadastro.getValueAt(modelCadastro.getRowCount() - 1, modelCadastro.getColumnCount() - 2))));
    }

    public void removerLinha() {
        DefaultTableModel modelCadastro = (DefaultTableModel) tabela.getModel();
        int cont = modelCadastro.getRowCount() - 1;
        int col = modelCadastro.getColumnCount() - 1;
        for (int i = 0; i < cont; i++) {
            for (int j = 0; j < col; j++) {
                if (est.getIdEst().equals(modelCadastro.getValueAt(i, j))) {
                    modelCadastro.removeRow(i);
                }
            }
        }
    }

    public double valorVenda(List<ItensVenda> itensVenda) {//PENDENTE

        double valorTotal = 0;

        for (ItensVenda item : itensVenda) {
            valorTotal += (item.getQuantItensVenda() * item.getIdEst().getVlrVendaEst());
        }
        return valorTotal;
    }

    public void zerarComponentes() {
        itensVenda = new ArrayList<>();
        venda = new Venda((vjc.getVendaCount() + 1), new Date(), funcionario);
        campoCodigo.setText("");
        campoQuantidade.setModel(new SpinnerNumberModel(1, 1, null, 1));
        campoNomeProduto.setText("");
        campoCategoria.setText("");
        campoUltimoProduto.setText("");
        DefaultTableModel table = (DefaultTableModel) tabela.getModel();
        table.setNumRows(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarProduto;
    private javax.swing.JButton btnFinalizarCompra;
    private javax.swing.JTextField campoCategoria;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextField campoNomeProduto;
    private javax.swing.JSpinner campoQuantidade;
    private javax.swing.JTextPane campoUltimoProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuCadastroEstoque;
    private javax.swing.JMenuItem menuCadastroProdutos;
    private javax.swing.JMenu menuConsulta;
    private javax.swing.JMenu menuLogo;
    private javax.swing.JMenu menuVendas;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
